### ISSUE TITLE
Add translatable texts

### ISSUE THREAD

**Issue by sergioloporto** [huler/cookie-acceptance#7]
Hello,

kind request to make the following texts (that are now hardcoded) available from props, so that the users can change the text - useful for non-English websites:
![image](https://user-images.githubusercontent.com/51946947/149750852-95f0b79e-c517-4f2c-810c-0d141fdfa1d3.png)
![image](https://user-images.githubusercontent.com/51946947/149751195-f3a52735-af96-41b9-beed-188b87fc95aa.png)

**Comment by joeflem** [comment]
@sergioloporto Thanks for raising this, this is a great suggestion.
